Repository hft-rcpsp-scheduling/rcpsp-data-provider, pull requests merged in 2022-11, with the labels that each got.

#32 Memory bug
  .doc/postman.md
  .postman/db.postman_collection.json
  .postman/full-set.postman_collection.json
  .postman/load-eval-solution.postman_collection.json
  .postman/load-get-data.postman_collection.json
  .postman/load-get-solution.postman_collection.json
  .postman/load-save-solution.postman_collection.json
  src/main/java/com/hft/provider/config/ResponseGCFilter.java
  src/main/java/com/hft/provider/controller/DataController.java
  src/main/java/com/hft/provider/controller/model/StoredSolution.java
  src/main/java/com/hft/provider/database/DatabaseService.java
  src/main/java/com/hft/provider/database/EntityMapper.java
  src/main/java/com/hft/provider/database/JobEntity.java
  src/main/java/com/hft/provider/database/JobRepo.java
  src/main/java/com/hft/provider/database/SolutionEntity.java
  src/main/java/com/hft/provider/database/SolutionRepo.java
  src/main/java/com/hft/provider/database/SolutionRepoEM.java
  src/main/java/com/hft/provider/database/SolutionRepoEMImpl.java
  src/main/java/com/hft/provider/database/jdbc/ProjectMapper.java
  src/main/java/com/hft/provider/database/jdbc/ProjectSelector.java
  src/main/java/com/hft/provider/database/jdbc/SolutionMapper.java
  src/main/java/com/hft/provider/database/jdbc/SolutionSelector.java
  src/main/java/com/hft/provider/database/utility/JsonParser.java
  src/test/java/com/hft/provider/controller/DataControllerTest.java
  src/test/java/com/hft/provider/controller/EvaluationControllerTest.java
  src/test/java/com/hft/provider/controller/GlobalExceptionHandlerTest.java
  src/test/java/com/hft/provider/database/JobEntityTest.java
  src/test/java/com/hft/provider/database/jdbc/ProjectSelectorTest.java
  src/test/java/com/hft/provider/database/utility/JsonParserTest.java
  src/test/java/utility/AssertExtension.java
Labels: type: enhancement, type: refactoring

#34 Add swap to VM
  .doc/deployment.md
Labels: type: documentation, type: enhancement

#33 Logging & Refactoring
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/hft/provider/controller/DataController.java
  src/main/java/com/hft/provider/controller/EvaluationController.java
  src/main/java/com/hft/provider/controller/VisualController.java
  src/main/java/com/hft/provider/database/DatabaseService.java
  src/main/java/com/hft/provider/database/EntityMapper.java
  src/main/java/com/hft/provider/database/ProjectRepoEMImpl.java
  src/main/java/com/hft/provider/database/jdbc/JdbcExecutor.java
  src/main/java/com/hft/provider/database/jdbc/SolutionSelector.java
  src/main/java/com/hft/provider/file/FileReader.java
  src/main/java/com/hft/provider/file/MakespanReader.java
  src/main/java/com/hft/provider/file/ProjectReader.java
  src/main/java/com/hft/provider/file/StatementReader.java
  src/test/java/com/hft/provider/controller/VisualControllerTest.java
  src/test/java/com/hft/provider/database/DatabaseServiceTest.java
  src/test/java/com/hft/provider/file/MakespanReaderTest.java
  src/test/java/com/hft/provider/file/ProjectReaderTest.java
  src/test/java/utility/DataGenerator.java
Labels: type: refactoring

#35 added detailed failing reasons
  src/main/java/com/hft/provider/eval/SolutionEvaluator.java
Labels: type: enhancement
